<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EpisodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('episodes')->insert([
            ['movie_id' => 1, 'episode' => 'Episode 1', 'title' => 'Crash Landing On You'],
            ['movie_id' => 1, 'episode' => 'Episode 2', 'title' => 'Crash Landing On'],
            ['movie_id' => 1, 'episode' => 'Episode 3', 'title' => 'Crash Landing'],
            ['movie_id' => 1, 'episode' => 'Episode 4', 'title' => 'Crash '],
            ['movie_id' => 1, 'episode' => 'Episode 5', 'title' => 'Landing On You'],
            ['movie_id' => 1, 'episode' => 'Episode 6', 'title' => 'Landing On'],
            ['movie_id' => 1, 'episode' => 'Episode 7', 'title' => 'Landing'],
            ['movie_id' => 1, 'episode' => 'Episode 8', 'title' => 'On You'],
            ['movie_id' => 1, 'episode' => 'Episode 9', 'title' => 'On'],
            ['movie_id' => 1, 'episode' => 'Episode 10', 'title' => 'You'],
            ['movie_id' => 2, 'episode' => 'Episode 1', 'title' => 'It Is Okay To Not Be Okay'],
            ['movie_id' => 2, 'episode' => 'Episode 2', 'title' => 'It Is Okay To Not Be'],
            ['movie_id' => 2, 'episode' => 'Episode 3', 'title' => 'It Is Okay To Not'],
            ['movie_id' => 2, 'episode' => 'Episode 4', 'title' => 'It Is Okay To'],
            ['movie_id' => 2, 'episode' => 'Episode 5', 'title' => 'It Is Okay'],
            ['movie_id' => 2, 'episode' => 'Episode 6', 'title' => 'It Is'],
            ['movie_id' => 2, 'episode' => 'Episode 7', 'title' => 'It'],
            ['movie_id' => 2, 'episode' => 'Episode 8', 'title' => 'Psycho But It Is Okay'],
            ['movie_id' => 2, 'episode' => 'Episode 9', 'title' => 'Psycho But It Is'],
            ['movie_id' => 2, 'episode' => 'Episode 10', 'title' => 'Psycho But It'],
            ['movie_id' => 2, 'episode' => 'Episode 11', 'title' => 'Psycho But'],
            ['movie_id' => 2, 'episode' => 'Episode 12', 'title' => 'Psycho'],
            ['movie_id' => 3, 'episode' => 'Episode 1', 'title' => 'Start Up'],
            ['movie_id' => 3, 'episode' => 'Episode 2', 'title' => 'Start U'],
            ['movie_id' => 3, 'episode' => 'Episode 3', 'title' => 'Start'],
            ['movie_id' => 3, 'episode' => 'Episode 4', 'title' => 'Star'],
            ['movie_id' => 3, 'episode' => 'Episode 5', 'title' => 'Sta'],
            ['movie_id' => 3, 'episode' => 'Episode 6', 'title' => 'St'],
            ['movie_id' => 3, 'episode' => 'Episode 7', 'title' => 'S'],
            ['movie_id' => 4, 'episode' => 'Episode 1', 'title' => 'Itaewon Class'],
            ['movie_id' => 4, 'episode' => 'Episode 2', 'title' => 'Itaewon Clas'],
            ['movie_id' => 4, 'episode' => 'Episode 3', 'title' => 'Itaewon Cla'],
            ['movie_id' => 4, 'episode' => 'Episode 4', 'title' => 'Itaewon Cl'],
            ['movie_id' => 4, 'episode' => 'Episode 5', 'title' => 'Itaewon C'],
            ['movie_id' => 4, 'episode' => 'Episode 6', 'title' => 'Itaewon'],
            ['movie_id' => 4, 'episode' => 'Episode 7', 'title' => 'Itaewo'],
            ['movie_id' => 4, 'episode' => 'Episode 8', 'title' => 'Itaew'],
            ['movie_id' => 4, 'episode' => 'Episode 9', 'title' => 'Itae'],
            ['movie_id' => 4, 'episode' => 'Episode 10', 'title' => 'Ita'],
            ['movie_id' => 4, 'episode' => 'Episode 11', 'title' => 'It'],
            ['movie_id' => 4, 'episode' => 'Episode 12', 'title' => 'I'],
            ['movie_id' => 5, 'episode' => 'Episode 1', 'title' => 'Mickey Mouse'],
            ['movie_id' => 5, 'episode' => 'Episode 2', 'title' => 'Mickey Mous'],
            ['movie_id' => 5, 'episode' => 'Episode 3', 'title' => 'Mickey Mou'],
            ['movie_id' => 5, 'episode' => 'Episode 4', 'title' => 'Mickey Mo'],
            ['movie_id' => 5, 'episode' => 'Episode 5', 'title' => 'Mickey M'],
            ['movie_id' => 5, 'episode' => 'Episode 6', 'title' => 'Mickey'],
            ['movie_id' => 5, 'episode' => 'Episode 7', 'title' => 'Micke'],
            ['movie_id' => 5, 'episode' => 'Episode 8', 'title' => 'Mick'],
            ['movie_id' => 5, 'episode' => 'Episode 9', 'title' => 'Mic'],
            ['movie_id' => 5, 'episode' => 'Episode 10', 'title' => 'Mi'],
            ['movie_id' => 5, 'episode' => 'Episode 11', 'title' => 'M'],
            ['movie_id' => 6, 'episode' => 'Episode 1', 'title' => 'Frozen'],
            ['movie_id' => 6, 'episode' => 'Episode 2', 'title' => 'Froze'],
            ['movie_id' => 6, 'episode' => 'Episode 3', 'title' => 'Froz'],
            ['movie_id' => 6, 'episode' => 'Episode 4', 'title' => 'Fro'],
            ['movie_id' => 6, 'episode' => 'Episode 5', 'title' => 'Fr'],
            ['movie_id' => 6, 'episode' => 'Episode 6', 'title' => 'F'],
            ['movie_id' => 7, 'episode' => 'Episode 1', 'title' => 'Sophia The First'],
            ['movie_id' => 7, 'episode' => 'Episode 2', 'title' => 'Sophia The'],
            ['movie_id' => 7, 'episode' => 'Episode 3', 'title' => 'Sophia'],
            ['movie_id' => 7, 'episode' => 'Episode 4', 'title' => 'The'],
            ['movie_id' => 7, 'episode' => 'Episode 5', 'title' => 'The First'],
            ['movie_id' => 7, 'episode' => 'Episode 6', 'title' => 'First'],
            ['movie_id' => 8, 'episode' => 'Episode 1', 'title' => 'Cocomelon'],
            ['movie_id' => 8, 'episode' => 'Episode 2', 'title' => 'Cocomelo'],
            ['movie_id' => 8, 'episode' => 'Episode 3', 'title' => 'Cocomel'],
            ['movie_id' => 8, 'episode' => 'Episode 4', 'title' => 'Cocome'],
            ['movie_id' => 8, 'episode' => 'Episode 5', 'title' => 'Cocom'],
            ['movie_id' => 8, 'episode' => 'Episode 6', 'title' => 'Coco'],
            ['movie_id' => 8, 'episode' => 'Episode 7', 'title' => 'Coc'],
            ['movie_id' => 8, 'episode' => 'Episode 8', 'title' => 'Co'],
            ['movie_id' => 8, 'episode' => 'Episode 9', 'title' => 'C'],
            ['movie_id' => 9, 'episode' => 'Episode 1', 'title' => 'Running Man'],
            ['movie_id' => 9, 'episode' => 'Episode 2', 'title' => 'Running Ma'],
            ['movie_id' => 9, 'episode' => 'Episode 3', 'title' => 'Running M'],
            ['movie_id' => 9, 'episode' => 'Episode 4', 'title' => 'Running'],
            ['movie_id' => 9, 'episode' => 'Episode 5', 'title' => 'Runnin'],
            ['movie_id' => 9, 'episode' => 'Episode 6', 'title' => 'Runni'],
            ['movie_id' => 9, 'episode' => 'Episode 7', 'title' => 'Runn'],
            ['movie_id' => 9, 'episode' => 'Episode 8', 'title' => 'Run'],
            ['movie_id' => 9, 'episode' => 'Episode 9', 'title' => 'Ru'],
            ['movie_id' => 9, 'episode' => 'Episode 10', 'title' => 'R'],
            ['movie_id' => 10, 'episode' => 'Episode 1', 'title' => 'Knowing Brothers'],
            ['movie_id' => 10, 'episode' => 'Episode 2', 'title' => 'Knowing Brother'],
            ['movie_id' => 10, 'episode' => 'Episode 3', 'title' => 'Knowing'],
            ['movie_id' => 10, 'episode' => 'Episode 4', 'title' => 'Brothers'],
            ['movie_id' => 10, 'episode' => 'Episode 5', 'title' => 'Brother'],
            ['movie_id' => 10, 'episode' => 'Episode 6', 'title' => 'Brother Knowing'],
            ['movie_id' => 10, 'episode' => 'Episode 7', 'title' => 'Brothers Knowing'],
            ['movie_id' => 10, 'episode' => 'Episode 8', 'title' => 'Know Brothers'],
            ['movie_id' => 10, 'episode' => 'Episode 9', 'title' => 'Know Brother'],
            ['movie_id' => 10, 'episode' => 'Episode 10', 'title' => 'Brother Know'],
            ['movie_id' => 10, 'episode' => 'Episode 11', 'title' => 'Brothers Knowing'],
            ['movie_id' => 10, 'episode' => 'Episode 12', 'title' => 'Kang Ho Dong'],
            ['movie_id' => 11, 'episode' => 'Episode 1', 'title' => 'Friends'],
            ['movie_id' => 11, 'episode' => 'Episode 2', 'title' => 'Friend'],
            ['movie_id' => 11, 'episode' => 'Episode 3', 'title' => 'Frien'],
            ['movie_id' => 11, 'episode' => 'Episode 4', 'title' => 'Frie'],
            ['movie_id' => 11, 'episode' => 'Episode 5', 'title' => 'Fri'],
            ['movie_id' => 11, 'episode' => 'Episode 6', 'title' => 'Fr'],
            ['movie_id' => 11, 'episode' => 'Episode 7', 'title' => 'F'],
            ['movie_id' => 12, 'episode' => 'Episode 1', 'title' => 'Happy Together'],
            ['movie_id' => 12, 'episode' => 'Episode 2', 'title' => 'Happy'],
            ['movie_id' => 12, 'episode' => 'Episode 3', 'title' => 'Together'],
            ['movie_id' => 12, 'episode' => 'Episode 4', 'title' => 'Together Happy'],
            ['movie_id' => 12, 'episode' => 'Episode 5', 'title' => 'Yoo Jae Suk'],
            ['movie_id' => 12, 'episode' => 'Episode 6', 'title' => 'Jo Se Ho']
        ]);
    }
}
